<?php 
//# JS
$this->headScript()->appendFile($this->basePath('public/js/OapDatamng/datamng_index.js?v='.$application_configs['ver']), 'text/javascript');
$this->headScript()->appendFile($this->basePath('public/js/OapDatamng/datamng_upload.js?v='.$application_configs['ver']), 'text/javascript');
$this->headScript()->appendFile($this->basePath('public/js/OapDatamng/datamng_crud.js?v='.$application_configs['ver']), 'text/javascript');
        
//# CSS
$this->headLink()->appendStylesheet($this->basePath('public/css/OapDatamng/datamng_index.css'));

global $_app_url;
?>
<script>
    var _user = '<?php echo $_username?>';
    var APPLICATION_URL = '<?php echo $this->basePath();?>'

    $( document ).ready(function() {
        'use strict';

        $('#caricamento').hide();
    });
</script>

<div class="pt-3 pb-2 mb-3 border-bottom">
    <h1>Datamng</h1>
</div>

<div class="container">
    <h2>Generic Upload</h2>
    <h3>File upload</h3>

    <input id="sortpicture" type="file" name="sortpic" />
    <button id="uploadimportfile" class="btn btn-primary brown csbutton chiudi_popup_ch">Conferma</button>
    
    <br><br>
    <h2>Uploaded files</h2>
    <?php
    $_APPLICATION_DATA_FOLDER = scandir($application_configs['APPLICATION_DATA_FOLDER'].'/datamng/uploaded');

    foreach ($_APPLICATION_DATA_FOLDER as $file){
        echo '<a class="openfile" href="'.$file.'">'.$file.'</a><br>';
    }    
    ?>

    <br><br>
    <h2>Table's Interfaces</h2>
    <input type="text" id="tablename" value="NPNDkW5Jsp"/>
    <button id="createCRUDcode">Create code</button>
    <?php
    //# TODO
    ?>
    <h3>Table Data</h3>
    <div id="tablecontent"></div>
    <h3>Menu</h3>
    <h4>/module/Application/view/layout/layout.phtml</h4>
    <textarea id="tablecontent_generated__menu"></textarea>
    <h3>Application config</h3>
    <h4>/-change-here.php</h4>
    <textarea id="tablecontent_generated__application_config"></textarea>
    <h3>Code generated - VIEW</h3>
    <h4>Module config View - code</h4 >
    <h5>module.config.php</h5>
    <textarea id="tablecontent_generated__moduleconfigview"></textarea>
    <h4>QUERY View - code</h4 >
    <textarea id="tablecontent_generated__query"></textarea>
    <h4>HTML View - code</h4>
    <h5>phtml</h5>
    <textarea id="tablecontent_generated__html"></textarea>
    <textarea id="tablecontent_generated__html_HTMLviewfield"></textarea>
    <textarea id="tablecontent_generated__html_JSviewfield"></textarea>
    
    
    <h4>JS View data - code</h4>
    <textarea id="tablecontent_generated__jsview"></textarea>
    <h4>PHP get data - code</h4>
    <textarea id="tablecontent_generated__phpview"></textarea>
    <br>
    <br>
    <h3>Code generated - EDIT/INSERT FORM</h3>
    <h4>Module config Edit - code</h4 >
    <h5>module.config.php</h5>
    <textarea id="tablecontent_generated__moduleconfigedit"></textarea>
    <h4>HTML Edit Form - code</h4 >
    <h5>phtml</h5>
    <textarea id="tablecontent_generated__htmledit"></textarea>
    <h4>JS Edit Form - code</h4>
    <textarea id="tablecontent_generated__jsedit"></textarea>
    <h4>PHP Edit Form - code</h4>
    <textarea id="tablecontent_generated__phpedit"></textarea>
    <br>
    <br>
    <br>
    <br>
</div>

<div id="message"></div>


<!-- MODAL -->
<div class="modal fade" id="view_filecontent" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <span id="_view_filecontent"></span>
            </div>
            <div class="modal-footer">
                <button id="confirm_upload" type="button" class="btn btn-primary">Upload</button>
            </div>
        </div>
    </div>
</div>
